@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "WATCHDOG_SCRIPT=%SCRIPT_DIR%..\powershell\watchdog.ps1"

if not exist "%WATCHDOG_SCRIPT%" (
  echo ERROR: Watchdog script not found at "%WATCHDOG_SCRIPT%".
  exit /b 1
)

if not defined WATCHDOG_UNREAL_PROCESS_NAME (
  if defined SCALEWORLD_RUNTIME_PROCESS_PATTERN (
    set "WATCHDOG_UNREAL_PROCESS_NAME=%SCALEWORLD_RUNTIME_PROCESS_PATTERN%"
  ) else if defined SCALEWORLD_EXECUTABLE_NAME (
    for %%I in ("%SCALEWORLD_EXECUTABLE_NAME%") do set "WATCHDOG_UNREAL_PROCESS_NAME=%%~nI-Win64-*"
  ) else (
    set "WATCHDOG_UNREAL_PROCESS_NAME=ScaleWorld-Win64-*"
  )
)

if not defined WATCHDOG_WILBUR_COMMANDLINE_PATTERN (
  for %%I in ("%SCRIPT_DIR%..\..") do set "WATCHDOG_WILBUR_COMMANDLINE_PATTERN=%%~fI"
)

if not defined WATCHDOG_TERMINATE_MATCHED_PROCESSES (
  set "WATCHDOG_TERMINATE_MATCHED_PROCESSES=true"
)

if not defined WATCHDOG_STREAMER_HEALTH_ENABLED (
  set "WATCHDOG_STREAMER_HEALTH_ENABLED=true"
)

if not defined WATCHDOG_STREAMER_HEALTH_PATH (
  set "WATCHDOG_STREAMER_HEALTH_PATH=state\streamer-health.json"
)

if not defined WATCHDOG_STREAMER_HEALTH_MAX_STALE_SECONDS (
  set "WATCHDOG_STREAMER_HEALTH_MAX_STALE_SECONDS=75"
)

if not defined WATCHDOG_STREAMER_HEALTH_STARTUP_GRACE_SECONDS (
  set "WATCHDOG_STREAMER_HEALTH_STARTUP_GRACE_SECONDS=120"
)

if not defined WATCHDOG_STREAMER_HEALTH_UNREADY_RECOVERY_SECONDS (
  set "WATCHDOG_STREAMER_HEALTH_UNREADY_RECOVERY_SECONDS=180"
)
if not defined WATCHDOG_PROVISIONING_STREAMER_HEALTH_STARTUP_GRACE_SECONDS (
  set "WATCHDOG_PROVISIONING_STREAMER_HEALTH_STARTUP_GRACE_SECONDS=3600"
)

if not defined WATCHDOG_PROVISIONING_ASSET_WARMUP_STALL_GRACE_SECONDS (
  set "WATCHDOG_PROVISIONING_ASSET_WARMUP_STALL_GRACE_SECONDS=1800"
)

if not defined WATCHDOG_PROVISIONING_ASSET_WARMUP_STALL_CPU_CONFIRM_SECONDS (
  set "WATCHDOG_PROVISIONING_ASSET_WARMUP_STALL_CPU_CONFIRM_SECONDS=120"
)

if not defined WATCHDOG_MAINTENANCE_MODE_REFRESH_SECONDS (
  set "WATCHDOG_MAINTENANCE_MODE_REFRESH_SECONDS=60"
)

if not defined WATCHDOG_UNREAL_CPU_STALL_CONFIRM_ENABLED (
  set "WATCHDOG_UNREAL_CPU_STALL_CONFIRM_ENABLED=true"
)

if not defined WATCHDOG_UNREAL_CPU_STALL_MIN_DELTA_SECONDS (
  set "WATCHDOG_UNREAL_CPU_STALL_MIN_DELTA_SECONDS=0.001"
)

if not defined WATCHDOG_UNREAL_CPU_STALL_CONFIRM_SECONDS (
  set "WATCHDOG_UNREAL_CPU_STALL_CONFIRM_SECONDS=10"
)

if not defined WATCHDOG_RESTART_COMMAND (
  set "WATCHDOG_RESTART_COMMAND=""%SCRIPT_DIR%start_streamer_stack.bat"" --recovery"
)

if not defined WATCHDOG_WILBUR_RESTART_COMMAND (
  set "WATCHDOG_WILBUR_RESTART_COMMAND=%WATCHDOG_RESTART_COMMAND%"
)

if not defined WATCHDOG_UNREAL_RESTART_COMMAND (
  set "WATCHDOG_UNREAL_RESTART_COMMAND=%WATCHDOG_RESTART_COMMAND%"
)

if not defined WATCHDOG_PROCESS_STARTUP_GRACE_SECONDS (
  set "WATCHDOG_PROCESS_STARTUP_GRACE_SECONDS=15"
)

powershell -NoProfile -ExecutionPolicy Bypass -File "%WATCHDOG_SCRIPT%" %*
exit /b %errorlevel%
